'use strict';

const mongoose = require('mongoose');

const addressSchema = new mongoose.Schema({
  OBJECTID:{
    type:Number
  },
  SSL:{
    type:String
  },
  ASSESSOR_NAME:{
    type:String
  },
  LAND_USE_CODE:{
    type:Number
  },
  LAND_USE_DESCRIPTION:{
    type:String
  },
  LANDAREA:{
    type:Number
  },
  PROPERTY_ADDRESS:{
    type:String
  },
  OTR_NEIGHBORHOOD_CODE:{
    type:Number
  },
  OTR_NEIGHBORHOOD_NAME:{
    type:String
  },
  OWNER_NAME_PRIMARY:{
    type:String
  },
  CAREOF_NAME:{
    type:String
  },
  OWNER_ADDRESS_LINE1:{
    type:String
  },
  OWNER_ADDRESS_LINE2:{
    type:String
  },
  OWNER_ADDRESS_CITYSTZIP:{
    type:String
  },
  APPRAISED_VALUE_BASEYEAR_LAND:{
    type:String
  },
  APPRAISED_VALUE_BASEYEAR_BLDG:{
    type:String
  },
  APPRAISED_VALUE_PRIOR_LAND:{
    type:String
  },
  APPRAISED_VALUE_PRIOR_IMPR:{
    type:String
  },
  APPRAISED_VALUE_PRIOR_TOTAL:{
    type:String
  },
  APPRAISED_VALUE_CURRENT_LAND:{
    type:String
  },
  APPRAISED_VALUE_CURRENT_IMPR:{
    type:String
  },
  APPRAISED_VALUE_CURRENT_TOTAL:{
    type:String
  },
  PHASEIN_VALUE_CURRENT_LAND:{
    type:String
  },
  PHASEIN_VALUE_CURRENT_BLDG:{
    type:String
  },
  VACANT_USE:{
    type:String
  },
  HOMESTEAD_DESCRIPTION:{
    type:String
  },
  TAX_TYPE_DESCRIPTION:{
    type:String
  },
  TAXRATE:{
    type:Number
  },
  MIXED_USE:{
    type:Number
  },
  OWNER_OCCUPIED_COOP_UNITS:{
    type:String
  },
  LAST_SALE_PRICE:{
    type:Number
  },
  LAST_SALE_DATE:{
    type:Date
  },
  DEED_DATE:{
    type:Date
  },
  CURRENT_ASSESSMENT_CAP:{
    type:String
  },
  PROPOSED_ASSESSMENT_CAP:{
    type:String
  },
  OWNER_NAME_SECONDARY:{
    type:String
  },
  ADDRESS_ID:{
    type:Number
  },
  LASTMODIFIEDDATE:{
    type:Date
  },

});

const Address = mongoose.model('Address', addressSchema);

module.exports = Address;
